package com.example.lab5.data.local.entities

import androidx.room.ColumnInfo
import androidx.room.Entity
import androidx.room.PrimaryKey
import com.example.lab5.data.model.MealType
import java.time.LocalDateTime

/**
 * Entity class representing a meal in the database.
 *
 * @property id Unique identifier for the meal (auto-generated by Room).
 * @property name Name of the meal (e.g., "Breakfast", "Chicken Salad").
 * @property calories Total calories in the meal.
 * @property protein Protein content in grams.
 * @property carbs Carbohydrates content in grams.
 * @property fat Fat content in grams.
 * @property dateTime Date and time when the meal was consumed.
 * @property userId ID of the user who logged this meal (for multi-user support).
 */
@Entity(tableName = "meals")
data class MealEntity(
    @PrimaryKey(autoGenerate = true)
    val id: Long = 0,

    @ColumnInfo(name = "name")
    val name: String,

    @ColumnInfo(name = "calories")
    val calories: Float,

    @ColumnInfo(name = "protein")
    val protein: Float,

    @ColumnInfo(name = "carbs")
    val carbs: Float,

    @ColumnInfo(name = "fat")
    val fat: Float,

    @ColumnInfo(name = "date_time")
    val dateTime: LocalDateTime,

    @ColumnInfo(name = "user_id")
    val userId: Long? = null, // Optional, for future multi-user support
    val mealType: MealType
)