package com.example.lab5.data.local.entities

import androidx.room.ColumnInfo
import androidx.room.Entity
import androidx.room.PrimaryKey
import java.util.Date

/**
 * Entity class representing user's daily nutrition goals in the database.
 *
 * @property id Unique identifier for the goal record (auto-generated by Room).
 * @property userId ID of the user who owns these goals (for multi-user support).
 * @property dailyCalories Target daily calories intake.
 * @property dailyProtein Target daily protein intake in grams.
 * @property dailyCarbs Target daily carbohydrates intake in grams.
 * @property dailyFat Target daily fat intake in grams.
 * @property isActive Flag indicating if these goals are currently active.
 */
@Entity(tableName = "nutrition_goals")
data class NutritionGoalEntity(
    @PrimaryKey(autoGenerate = true)
    val id: Long = 0,

    @ColumnInfo(name = "user_id", defaultValue = "0")
    val userId: Long,

    @ColumnInfo(name = "daily_calories")
    val dailyCalories: Float,

    @ColumnInfo(name = "daily_protein")
    val dailyProtein: Float,

    @ColumnInfo(name = "daily_carbs")
    val dailyCarbs: Float,

    @ColumnInfo(name = "daily_fat")
    val dailyFat: Float,

    @ColumnInfo(name = "is_active", defaultValue = "true")
    val isActive: Boolean = true,
    val startDate: Date,
    val endDate: Date?
)

data class DailyNutritionSummaryEntity(
    val calories: Float,
    val protein: Float,
    val carbs: Float,
    val fat: Float
)