package com.example.lab5.data.local.entities

import androidx.room.ColumnInfo
import androidx.room.Entity
import androidx.room.PrimaryKey
import java.time.LocalDate
import java.util.Date

/**
 * Entity class representing a user in the database.
 *
 * @property id Unique identifier for the user (auto-generated by Room)
 * @property email User's email address (used for authentication)
 * @property password Hashed password (use proper hashing like bcrypt in production)
 * @property name User's display name
 * @property birthDate User's date of birth (nullable for optional field)
 * @property height User's height in centimeters (nullable)
 * @property weight User's weight in kilograms (nullable)
 * @property gender User's gender (nullable)
 * @property createdAt Timestamp when user was created (auto-set)
 */
@Entity(tableName = "users")
data class UserEntity(
    @PrimaryKey(autoGenerate = true)
    val id: Long = 0,

    @ColumnInfo(name = "email", index = true)
    val email: String,

    @ColumnInfo(name = "password")
    val password: String,

    @ColumnInfo(name = "name")
    val name: String,

    @ColumnInfo(name = "birth_date")
    val birthDate: Date? = null,

    @ColumnInfo(name = "height")
    val height: Int? = null,

    @ColumnInfo(name = "weight")
    val weight: Float? = null,

    @ColumnInfo(name = "gender")
    val gender: String? = null,

    @ColumnInfo(name = "created_at")
    val createdAt: Date = Date()
)